### ISSUE TITLE
Error when creating a new table with 7.1.6

### ISSUE THREAD

**Issue by TerryLines** [kineticadb/kinetica-api-python#13]
Creating a table by passing _type,name,db arguments to gpudb.GPUdbTable() raises an error. The same code works for 7.1.5

> Traceback (most recent call last):
>   File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/ec2-user/etl/etl/infutor_load_direct.py", line 419, in <module>
>     load_tch_address()
>   File "/home/ec2-user/etl/etl/infutor_load_direct.py", line 335, in load_tch_address
>     db=db,
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/gpudb/gpudb.py", line 35262, in __init__
>     "".format( e ) )
> gpudb.gpudb.GPUdbException: 'Error creating GPUdbTable: \'"Error: \'Parameter map key: \'create_temp_table\' is not a valid parameter (U/PUh:348); error in Job validation\'"\''

**Comment by durika** [comment]
Hi, can you please share the code snippet that causes this?

**Comment by kylesutton** [comment]
This should be fixed in v7.1.6.1.  Let me know if you have any further issues.

Thanks,
Kyle
