### ISSUE TITLE
tabulate import problems 

### ISSUE THREAD

**Issue by TerryLines** [kineticadb/kinetica-api-python#14]
gpudb.py module adds the gpudb_module_path to sys.path. This is causing the bundled version of tabulate (0.7.5 to be loaded) even if a newer version exists in the environment - in particular tabulate 0.8.7 is required by pandas.to_markdown(). Can the gpudb_module_path be appended to the end of sys.path rather than the front?

```
# Search for our modules first, probably don't need imp or virt envs.
if not GPUDB_MODULE_PATH in sys.path :
    sys.path.insert(len(sys.path), GPUDB_MODULE_PATH)
if not GPUDB_MODULE_PATH + "/packages" in sys.path :
    sys.path.insert(len(sys.path), GPUDB_MODULE_PATH + "/packages")

```

**Comment by kylesutton** [comment]
@TerryLines - this should be fixed in v7.1.8.4.  Let me know if that version solves the issue for you.

Thanks,
Kyle
