### ISSUE TITLE
The maximum row number retrieved from Kinetica Table is 20.000, even i defined limit more than 20 K

### ISSUE THREAD

**Issue by SadiCetinkaya** [kineticadb/kinetica-api-python#2]
Hi All,

As given in kinetica python api example, I get records from the one of our Kineticadb table via python udf. However, it gets maximum 20.000 row even i define the limit as 300.000 in code below.  

`KINETICA_HOST = '10.20.10.228'
    KINETICA_PORT = '9191'

    h_db = gpudb.GPUdb(encoding = 'BINARY', host = KINETICA_HOST, port = KINETICA_PORT)

    response = h_db.get_records( table_name = "udf_json_example",limit = 200000,
                                 encoding = "binary")

    tablo = gpudb.GPUdbRecord.decode_binary_data(response["type_schema"], response["records_binary"])
`

**Comment by jmesney** [comment]
The 20k limit is configurable. Please stop Kinetica, edit /opt/gpudb/core/etc/gpudb.conf (or use the admin UI) and change this line:-

```# Maximum number of records that data retrieval requests such as
# /get/records and /aggregate/groupby will return per request.
max_get_records_size = 20000
```

Then start Kinetica again.

**Comment by SadiCetinkaya** [comment]
Thanks @jmesney it works now.

**Comment by mmahmud** [comment]
Hi Sadi,

Another way to configure that property without stopping Kinetica is to use
the *alter_system_properties()* function (
https://www.kinetica.com/docs/api/python/source/gpudb.html?highlight=alter_system_properties#gpudb.GPUdb.alter_system_properties).
You can use the *max_get_records_size* property to set the value.

Thanks!
