### ISSUE TITLE
Version 7.0 is incompatible with Kinetica 6.2

### ISSUE THREAD

**Issue by petrvecera** [kineticadb/kinetica-api-python#7]
Hi guys

When you are running instance of the Kinetica DB which is version 6.2 and you are trying to connect with python gpudb 7.0 it ends up in this error:
```
python_1    | Traceback (most recent call last):
python_1    |   File "/app/deploy.py", line 83, in <module>
python_1    |     main()
python_1    |   File "/app/deploy.py", line 9, in main
python_1    |     db = gpudb.GPUdb(host=config.GPUDB_HOST, port=config.GPUDB_PORT)
python_1    |   File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 2167, in __init__
python_1    |     **kwargs )
python_1    |   File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 2293, in __construct
python_1    |     server_status_response = self.show_system_status()
python_1    |   File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 16470, in show_system_status
python_1    |     response = self.__post_then_get_cext( REQ_SCHEMA, RSP_SCHEMA, obj, '/show/system/status' )
python_1    |   File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 3048, in __post_then_get_cext
python_1    |     return self.__read_datum_cext(REP_SCHEMA, response, None, response_time)
python_1    |   File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 2948, in __read_datum_cext
python_1    |     out = SCHEMA.decode( encoded_datum, resp['data'] )
python_1    | EOFError: incomplete binary data
```

**The incompatibility is fine** and could be expected but it would be nice **if there was better error.** From this ^^ you are not able to determine where is the problem and if you have in your requirements something like `gpudb>=6.2.0.10` you might run into this problem. 

Thanks

**Comment by mmahmud** [comment]
Hello Petr,

The 6.2 python API is actually significantly incompatible with the 7.0
server (extensive changes were made), and you should use the matching API
(i.e. the first two components need to match only).  The API does a
handshake and prints a warning at the start-up warning the user of this
mismatch.  I've just added a note to the README bringing attention to this
so that it is not confusing.

Please ensure that you're using the appropriate client.  You can also
install the API from PyPI by invoking "pip install gpudb==6.2.x.y" (or "pip
install gpudb" for the latest 7.0.a.b version).  That would be the easiest
way of installing the API.

Please let us know if you run into any further issues.

Thanks!

**Comment by petrvecera** [comment]
Hi @mmahmud . Yes I understand that the versions are not compatible, **but this bug report is about the statement bellow which is not true:**

> The API does a handshake and prints a warning at the start-up warning the user of this mismatch

**There is no warning. Please follow the steps to reproduce bellow:**

**Simplified steps:**
1. Startup Kinetica 6.2
2. Install Python GPUDB 7.0
3. Try to connect using this library to Kinetica

**Expected result**: Clear error that these versions are not compatible.
**Actual result**: Random error which doesn't tell you what is going on. 

**Full steps:**

My dockerfile:
```
FROM kinetica/kinetica-intel:6.2.0

ENV LICENSE_KEY ""
ENV FULL_START 1

RUN sed -i "s#license_key.*#license_key = ${LICENSE_KEY}#" /opt/gpudb/core/etc/gpudb.conf
RUN ldconfig

ENTRYPOINT ["/bin/bash", "/opt/gpudb-docker-start.sh"]
```
Terminal:
`docker build . -t test_kinetica`
`docker run -p 8080:8080 -p 9191:9191  test_kinetica`

Now I verify that UI is working on `localhost:8080` and `localhost:9191` is returning `Kinetica is running!`

My python file:
```
import gpudb
db = gpudb.GPUdb(host="localhost", port="9191")
```
gpudb version is 7.0.0

Result:
```
/usr/bin/python3.6 /home/petrvecera/Git/profiq/kinetica/tests/test.py
Traceback (most recent call last):
  File "/home/petrvecera/Git/profiq/kinetica/tests/test.py", line 3, in <module>
    db = gpudb.GPUdb(host="localhost", port="9191")
  File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 2167, in __init__
    **kwargs )
  File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 2293, in __construct
    server_status_response = self.show_system_status()
  File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 16470, in show_system_status
    response = self.__post_then_get_cext( REQ_SCHEMA, RSP_SCHEMA, obj, '/show/system/status' )
  File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 3048, in __post_then_get_cext
    return self.__read_datum_cext(REP_SCHEMA, response, None, response_time)
  File "/usr/local/lib/python3.6/dist-packages/gpudb/gpudb.py", line 2948, in __read_datum_cext
    out = SCHEMA.decode( encoded_datum, resp['data'] )
EOFError: incomplete binary data
```

**Comment by petrvecera** [comment]
If you look at the line 2293 of the gpudb.py

```
        # Make sure that a connection to the server can be established
        self.no_init_db_contact = no_init_db_contact
        if not self.no_init_db_contact:
            server_status_response = self.show_system_status()
            if not _Util.is_ok( server_status_response ):
                raise GPUdbException( _Util.get_error_msg( server_status_response ) )


        # Check version compatibility with the server
        # -------------------------------------------
        if not no_init_db_contact:
            self._perform_version_check()
```

It's crashing on the command `server_status_response = self.show_system_status()` which is before `self._perform_version_check()` is run.

**Comment by mmahmud** [comment]
Hi Petr,

Good catch!  I'm working on putting in a fix.  We'll throw a GPUdbException
in this scenario.  This should be in by the end of the week.

Thanks!
